services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "config.asgi:application"]

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

