services:
  web:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "config.asgi:application"]
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/dbname
    depends_on:
      - postgres

#   frontend:
#     images: nginx:latest
#     volumes:
#       - ./frontend:/usr/src/app
#     ports:
#       - "3000:3000"
#     environment:
#       - NODE_ENV=development
#     command: ["npm", "start"]

  redis:
    image: redis:latest
    ports:
      - "6380:6379"

# Additional services like db, etc.
postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
