# Generated by Django 5.1.4 on 2025-01-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('score_player1', models.PositiveIntegerField(default=0)),
                ('score_player2', models.PositiveIntegerField(default=0)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('player1', models.ForeignKey(help_text='First player in the match', on_delete=django.db.models.deletion.CASCADE, related_name='player1_matches', to='accounts.player')),
                ('player2', models.ForeignKey(help_text='Second player in the match', on_delete=django.db.models.deletion.CASCADE, related_name='player2_matches', to='accounts.player')),
                ('winner', models.ForeignKey(blank=True, help_text='Player who won the match', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='accounts.player')),
            ],
        ),
    ]
