# Generated by Django 5.1.4 on 2025-01-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the game room is active')),
                ('max_players', models.PositiveIntegerField(default=2, help_text='Maximum number of players allowed in the room')),
                ('channel_layer_key', models.CharField(blank=True, help_text='Key to identify the room in Redis/Channels', max_length=255, null=True)),
                ('host', models.ForeignKey(help_text='Player hosting the room', on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to='accounts.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
