# Generated by Django 5.1.4 on 2025-01-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('game', '0001_initial'),
        ('matchmaking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='match',
            field=models.OneToOneField(help_text='The match associated with this game room', on_delete=django.db.models.deletion.CASCADE, related_name='game_room', to='matchmaking.match'),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='players',
            field=models.ManyToManyField(help_text='Players currently in the room', related_name='game_rooms', to='accounts.player'),
        ),
    ]
